dist: trusty
sudo: false 

language: python

addons:
  apt:
    packages:
    - python-matplotlib 

python: 
  - "3.4"
  - "3.5"
  - "3.6"

  
install:
    
    - pip3 install .

script:
    - python chModeler.py -i 5 -s False
