dist: trusty
sudo: false 

language: python

addons:
  apt:
    packages:
    - python-matplotlib 

python: 
  - "3.2"
  - "3.4"
  - "3.5"
  - "3.6"
  - "3.7"
  - "3.8"

  
install:
    
    - pip3 install .

script:
    - python chModeler.py -i 5 -s False
